export const Const = {
  Brand: "Sonal & Kush",
  ClientLink: "https://www.sonalskushie.com",
  Desc:'Celebrate the wedding of Sonal & Kush. Find itinerary, venue details, hotel information & RSVP.',
  keywords:[
    "wedding website",
  "wedding planning website",
  "wedding invitation website",
  "online wedding invitation",
  "wedding RSVP website",
  "digital wedding card",
  "wedding website builder",
  "create wedding website",
  "online wedding invitations",
  "wedding e-invite",
  "RSVP wedding website",
  "wedding guest management",
  "send wedding invitations online",
  "wedding save the date website",
  "wedding website templates",
  "modern wedding website design",
  "luxury wedding website",
  "elegant wedding invitation website",
  "custom wedding website",
  "creative wedding website ideas",
  "wedding website India",
  "Indian wedding invitation website",
  "Punjabi wedding website",
  "wedding website in Punjab",
  "destination wedding website",
  "wedding photo gallery website",
  "wedding countdown website",
  "wedding event schedule website",
  "couple story wedding website",
  "wedding registry website",
  "free wedding website builder",
  "best wedding website platforms",
  "wedding website with RSVP",
  "mobile friendly wedding website",
  "create free wedding website with RSVP",
  "best wedding website for Indian weddings",
  "how to make wedding invitation website",
  "wedding website with custom domain",
  "affordable wedding website builder"
  ]
};